// <auto-generated />
using System;
using CopaHAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopaHAS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260526112825_Solucao")]
    partial class Solucao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstadioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadioId");

                    b.ToTable("TB_JOGOS", (string)null);
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.JogoSelecao", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Gols")
                        .HasColumnType("int");

                    b.Property<int>("GolsDecisaoPenalti")
                        .HasColumnType("int");

                    b.Property<int>("GolsProrrogacao")
                        .HasColumnType("int");

                    b.HasKey("JogoId", "SelecaoId");

                    b.HasIndex("SelecaoId");

                    b.ToTable("TB_JOGOS_SELECOES", (string)null);
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Selecao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TBL_SELECOES", (string)null);
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId")
                        .IsUnique();

                    b.ToTable("TB_TECNICOS", (string)null);
                });

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 600000,
                            Cidade = "São Paulo 1",
                            Nome = "Neo Quimica 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 600000,
                            Cidade = "São Paulo 2",
                            Nome = "Neo Quimica 2"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 600000,
                            Cidade = "São Paulo 3",
                            Nome = "Neo Quimica 3"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 600000,
                            Cidade = "São Paulo 4",
                            Nome = "Neo Quimica 4"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 600000,
                            Cidade = "São Paulo 5",
                            Nome = "Neo Quimica 5"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = 600000,
                            Cidade = "São Paulo 6",
                            Nome = "Neo Quimica 6"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = 600000,
                            Cidade = "São Paulo 7",
                            Nome = "Neo Quimica 7"
                        });
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int?>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SelecaoId");

                    b.ToTable("TBL_JOGADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hugo Souza",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Yuri Alberto",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Danilo",
                            NumeroCamisa = 2,
                            Posicao = "Lateral Direito",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Marquinhos",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Casemiro",
                            NumeroCamisa = 5,
                            Posicao = "Volante",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Alex Sandro",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Lucas Paquetá",
                            NumeroCamisa = 7,
                            Posicao = "Meio Campo",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bruno Guimarães",
                            NumeroCamisa = 8,
                            Posicao = "Meio Campo",
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Richarlison",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Vinicius Jr",
                            NumeroCamisa = 11,
                            Posicao = "Atacante",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Rodrygo",
                            NumeroCamisa = 19,
                            Posicao = "Atacante",
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Alisson",
                            NumeroCamisa = 23,
                            Posicao = "Goleiro",
                            Status = 4
                        });
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Jogo", b =>
                {
                    b.HasOne("CopaHAS.Models.Estadio", "EstadioIdNavegacao")
                        .WithMany("Jogos")
                        .HasForeignKey("EstadioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadioIdNavegacao");
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.JogoSelecao", b =>
                {
                    b.HasOne("AvaliacaoCopaHAS.Models.Jogo", "JogoIdNavegacao")
                        .WithMany("Jogoselecoes")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvaliacaoCopaHAS.Models.Selecao", "SelecaoIdNavegacao")
                        .WithMany("JogosSelecoes")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JogoIdNavegacao");

                    b.Navigation("SelecaoIdNavegacao");
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Tecnico", b =>
                {
                    b.HasOne("AvaliacaoCopaHAS.Models.Selecao", "SelecaoIdNavegacao")
                        .WithOne("Tecnico")
                        .HasForeignKey("AvaliacaoCopaHAS.Models.Tecnico", "SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SelecaoIdNavegacao");
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.HasOne("AvaliacaoCopaHAS.Models.Selecao", "SelecaoIdNavegacao")
                        .WithMany("Jogadores")
                        .HasForeignKey("SelecaoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("SelecaoIdNavegacao");
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Jogo", b =>
                {
                    b.Navigation("Jogoselecoes");
                });

            modelBuilder.Entity("AvaliacaoCopaHAS.Models.Selecao", b =>
                {
                    b.Navigation("Jogadores");

                    b.Navigation("JogosSelecoes");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
