// <auto-generated />
using CopaHAS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CopaHAS.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260406110117_MigracaoEstadios")]
    partial class MigracaoEstadios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CopaHAS.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 600000,
                            Cidade = "São Paulo 1",
                            Nome = "Neo Quimica 1"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 600000,
                            Cidade = "São Paulo 2",
                            Nome = "Neo Quimica 2"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 600000,
                            Cidade = "São Paulo 3",
                            Nome = "Neo Quimica 3"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 600000,
                            Cidade = "São Paulo 4",
                            Nome = "Neo Quimica 4"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 600000,
                            Cidade = "São Paulo 5",
                            Nome = "Neo Quimica 5"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = 600000,
                            Cidade = "São Paulo 6",
                            Nome = "Neo Quimica 6"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = 600000,
                            Cidade = "São Paulo 7",
                            Nome = "Neo Quimica 7"
                        });
                });

            modelBuilder.Entity("CopaHAS.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_JOGADORES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Hugo Souza",
                            NumeroCamisa = 1,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Yuri Alberto",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Danilo",
                            NumeroCamisa = 2,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Marquinhos",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Casemiro",
                            NumeroCamisa = 5,
                            Posicao = "Volante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Alex Sandro",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Lucas Paquetá",
                            NumeroCamisa = 7,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Bruno Guimarães",
                            NumeroCamisa = 8,
                            Posicao = "Meio Campo",
                            SelecaoId = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Richarlison",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Vinicius Jr",
                            NumeroCamisa = 11,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Rodrygo",
                            NumeroCamisa = 19,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 3
                        },
                        new
                        {
                            Id = 12,
                            Nome = "Alisson",
                            NumeroCamisa = 23,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
